// src/components/convert/module.tsx
import React from 'react'
import type { PropsWithChildren } from 'react'

import { classify } from '../../utils'

type ModuleProps = PropsWithChildren<{
  /** A `text-[color]` tailwind class. */
  color: string
  className?: string
  /** The name of the module. */
  name: string
}>

/**
 * Converter module.
 */
const Module = ({
  color,
  className = '',
  children,
  name
}: ModuleProps): JSX.Element => (
  <form name={name} className='mt-3 sm:mt-6'>
    <fieldset className={classify('p-3 border-2 border-slate rounded-lg', className)}>
      <legend className={classify('mx-2 px-2 border-2 border-slate rounded-md font-serif font-bold', color)}>{name}</legend>
      {children}
    </fieldset>
  </form>
)

export default Module

// src/routes/convert/Module.svelte
<script lang="ts">
  import { classnames } from '$lib'

  export let name: string | null | undefined
  export let color = ''
  let className = ''
  export let styleColor = ''
  export { className as class }
</script>

<form {name} class="mt-3 sm:mt-6">
  <fieldset class={classnames('rounded-lg border-2 border-slate p-3', className)}>
    <legend
      class={classnames('mx-2 rounded-md border-2 border-slate px-2 font-serif font-bold', color)}
      style:color={styleColor ?? 'revert'}
    >
      {name}
    </legend>

    <slot />
  </fieldset>
</form>
