// src/components/module.tsx
import React from 'react'
import type { PropsWithChildren } from 'react'

import { classify } from '../utils'

type ModuleProps = PropsWithChildren<{
  borderColor: string
  className?: string
  name: string
}>

/**
 * Converter module.
 */
const Module = ({
  borderColor,
  className = '',
  children,
  name
}: ModuleProps): JSX.Element => (
  <form name={name}>
    <fieldset className={classify('p-3 border-2 rounded-lg', `border-${borderColor}`, className)}>
      <legend className={classify('mx-2 px-2 border-2 rounded-md font-bold', `border-${borderColor}`)}>{name}</legend>
      {children}
    </fieldset>
  </form>
)

export default Module

// src/routes/convert/Module.svelte
<script lang="ts">
  import { classnames } from '$lib'

  export let name: string | null | undefined
  export let legendClass = ''
  export let fieldsetClass = ''
</script>

<form {name} class="mt-3 sm:mt-6">
  <fieldset class={classnames('rounded-lg border-2 border-slate p-3', fieldsetClass)}>
    <legend
      class={classnames(
        'mx-2 rounded-md border-2 border-slate px-2 font-serif font-bold',
        legendClass
      )}
    >
      {name}
    </legend>

    <slot />
  </fieldset>
</form>
